// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektBlazor.API.Data;

#nullable disable

namespace ProjektBlazor.API.Migrations
{
    [DbContext(typeof(KinoDbContext))]
    [Migration("20230517145844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektBlazor.API.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data_filmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dlugosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data_filmu = "9:00 22.08.2023",
                            Dlugosc = "168min",
                            Nazwa = "Kot w butach",
                            SalaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Data_filmu = "9:00 22.08.2023",
                            Dlugosc = "168min",
                            Nazwa = "Kot w butach 2",
                            SalaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Data_filmu = "9:00 22.08.2023",
                            Dlugosc = "168min",
                            Nazwa = "Kot w butach 3",
                            SalaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Data_filmu = "9:00 22.08.2023",
                            Dlugosc = "168min",
                            Nazwa = "Kot w butach 4",
                            SalaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Data_filmu = "9:00 22.08.2023",
                            Dlugosc = "168min",
                            Nazwa = "Kot w butach 5",
                            SalaId = 1
                        });
                });

            modelBuilder.Entity("ProjektBlazor.API.Entities.Miejsce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numer")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rzad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Miejsca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            Imie = "",
                            Nazwisko = "",
                            Numer = 1,
                            Phone = "",
                            Rzad = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            Imie = "",
                            Nazwisko = "",
                            Numer = 2,
                            Phone = "",
                            Rzad = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "",
                            Imie = "",
                            Nazwisko = "",
                            Numer = 3,
                            Phone = "",
                            Rzad = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "",
                            Imie = "",
                            Nazwisko = "",
                            Numer = 4,
                            Phone = "",
                            Rzad = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "",
                            Imie = "",
                            Nazwisko = "",
                            Numer = 5,
                            Phone = "",
                            Rzad = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "",
                            Imie = "",
                            Nazwisko = "",
                            Numer = 6,
                            Phone = "",
                            Rzad = 1
                        });
                });

            modelBuilder.Entity("ProjektBlazor.API.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<int>("MiejsceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sale");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LiczbaMiejsc = 40,
                            MiejsceID = 1
                        },
                        new
                        {
                            Id = 2,
                            LiczbaMiejsc = 52,
                            MiejsceID = 2
                        },
                        new
                        {
                            Id = 3,
                            LiczbaMiejsc = 46,
                            MiejsceID = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
